#!/usr/bin/env bash

rm -rf env activate
virtualenv --python=python3 env
ln -s env/bin/activate ./activate
source ./activate
pip install pillow
pip install pytz
pip install filelock
git submodule update --init
cd buydisplay-epaper26-example-adaptation/wiringpi/
make
